#!/usr/bin/with-contenv bash
# shellcheck shell=bash

IFS="|" read -r -a CLI_OPTIONS <<< "$CLI_OPTIONS_STRING"

if [[ $(tr "[:upper:]" "[:lower:]" <<<"${KOMETA_RUN}") = "true" ]] || echo "${CLI_OPTIONS[@]}" | grep -qPo '([\s]|^)(--run|--tests|--run-collections|--run-libraries|--run-files|--resume|-r|-ts|-rc|-rl|-rf|-re)([\s]|$)'; then
    rm -rf /etc/s6-overlay/s6-rc.d/svc-kometa
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/svc-kometa
    mkdir -p /etc/s6-overlay/s6-rc.d/user2/contents.d/
    touch /etc/s6-overlay/s6-rc.d/user2/contents.d/init-kometa-shutdown
else
    rm -rf /etc/s6-overlay/s6-rc.d/init-kometa-oneshot
    rm -rf /etc/s6-overlay/s6-rc.d/user/contents.d/init-kometa-oneshot
fi

exec \
    /docker-mods
